name: CI

on:
  push:
    branches: [ evelop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set-up Node
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build